### ISSUE TITLE
Support serial build of Amber 16

### ISSUE THREAD

**Issue by edmondac** [hpcugent/easybuild-easyblocks#1009]
Amber 16 sanity checks fail as the non-MPI build still looks for MPI files.

**Comment by edmondac** [comment]
I've done the work for this, just working out how to assign it to myself...

**Comment by boegel** [comment]
@edmondac best thing to do is just open a pull request for the changes you've made, and then refer to the easyblocks PR in the easyconfigs PR for Amber 16

**Comment by boegel** [comment]
@edmondac fixed in #1013? if so, please close this issue, we'll follow up in the PR
