### ISSUE TITLE
QuantumEspresso 6.0 need an updatead easyblock

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-easyblocks#1017]
QM-espresso 6.0 have changed name of among others make.sys to make.inc and some other things.

Have started making a patch and will submit PR when ready.

**Comment by akesandgren** [comment]
This may already be in progress. I just found a easyconfig issue referring to an easyblock change.

**Comment by boegel** [comment]
@akesandgren this should indeed by fixed by #1007 

I'll close this for now, don't hesitate to open it again in case you run into problems.
