### ISSUE TITLE
Intel MPI with Intel Fortran compiler must use mpiifort to be fully usable

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-easyblocks#1045]
Not sure if this should be in framework or in the easyblock section...

The current setup of impi is that is sets the env vars:
I_MPI_F77=ifort
I_MPI_F90=ifort
I_MPI_FC=ifort
and uses mpif90

However, for complete Fortran90 support and the MPI fortran module (USE mpi in fortran code)
it really have to use mpiifort. A short example of why.

cat t-mpi_mod.f90 
`           PROGRAM main
           USE mpi
           INTEGER :: comm, amode, info, fh, ierror
           CHARACTER(LEN=1) :: filename
           CALL MPI_File_open( comm, filename, amode, info, fh, ierror)
           END
`

mpif90 -c t-mpi_mod.f90 -v
mpif90 for the Intel(R) MPI Library 2017 Update 1 for Linux*
Copyright(C) 2003-2016, Intel Corporation.  All rights reserved.
ifort version 17.0.1
/pfs/software/eb/amd64_ubuntu1604_bdw/software/Core/ifort/2017.1.132-GCC-5.4.0-2.26/compilers_and_libraries_2017.1.132/linux/bin/intel64/fortcom
...
#include "..." search starts here:
#include <...> search starts here:
 .
 /hpc2n/eb/software/Compiler/intel/2017.1.132-GCC-5.4.0-2.26/impi/2017.1.132/intel64/include/gfortran/5.1.0
 /hpc2n/eb/software/Compiler/intel/2017.1.132-GCC-5.4.0-2.26/impi/2017.1.132/intel64/include
...
End of search list.
t-mpi_mod.f90(2): error #7013: This module file was not generated by any release of this compiler.   [MPI]
           USE mpi

While with mpiifort one gets:
mpiifort -c t-mpi_mod.f90 -v
mpiifort for the Intel(R) MPI Library 2017 Update 1 for Linux*
Copyright(C) 2003-2016, Intel Corporation.  All rights reserved.
ifort version 17.0.1
/pfs/software/eb/amd64_ubuntu1604_bdw/software/Core/ifort/2017.1.132-GCC-5.4.0-2.26/compilers_and_libraries_2017.1.132/linux/bin/intel64/fortcom
...
#include "..." search starts here:
#include <...> search starts here:
 .
 /hpc2n/eb/software/Compiler/intel/2017.1.132-GCC-5.4.0-2.26/impi/2017.1.132/intel64/include
...
 /usr/include
End of search list.
b-an01 [ake]$                       

and a successful compile.

**Comment by boegel** [comment]
@akesandgren this concerns the toolchain support, do you mind reopening this in https://github.com/hpcugent/easybuild-framework/issues?

**Comment by akesandgren** [comment]
Reopened in framework, closing

**Comment by boegel** [comment]
see https://github.com/hpcugent/easybuild-framework/issues/2000
