### ISSUE TITLE
OpenSSL 1.1.0 sanity check issue

### ISSUE THREAD

**Issue by vanzod** [hpcugent/easybuild-easyblocks#1085]
The sanity check For OpenSSL 1.1.0 fails since the library files names are hard coded into the easyblock and with the newer version number they do not match anymore.
I would suggest moving the path to the easyconfig files. Thoughts?

**Comment by boegel** [comment]
@vanzod we usually deal with this sort of thing by including a version check in the easyblock, where we use the new library names for newer versions, and stick to the old names for old versions

Doing this in the easyblock is a do-once-and-forget thing, while moving the `sanity_check_paths` in the easyconfigs means we're duplicating that info all over the place (which is already a problem for other stuff though).

Anything involving logic/version checks should ideally be done in the easyblock.

**Comment by boegel** [comment]
follow-up in #1087
