### ISSUE TITLE
WPS fails to build when we use system libpng or zlib

### ISSUE THREAD

**Issue by mboisson** [hpcugent/easybuild-easyblocks#1149]
Hi,
WPS fails to build when we use the system (or nix in our case) libpng and zlib. It expects it to have them in module without exception. 

I am not sure how we should fix this. It uses get_software_root(...) and fails if it is not found. I would expect that when 
filter-deps
is set (which we do for dependencies that are installed through the OS/nix), this function should return some path related to the OS.

Thoughts ?

Thanks,

Maxime Boissonneault

**Comment by boegel** [comment]
see https://github.com/hpcugent/easybuild-framework/issues/1494, which is basically a duplicate of this issue, let's follow up there?

**Comment by mboisson** [comment]
Oh, my bad.
