### ISSUE TITLE
Boost TIME_UTC patch needs to be applied to <= 1.49

### ISSUE THREAD

**Issue by school19** [hpcugent/easybuild-easyblocks#1151]
Currently the TIME_UTC patch is only applied to Boost versions <= 1.47, but the problem is only fixed in the Boost libraries in version 1.50.

Attempts to build Boost at version 1.49 results in compilation errors with anything that includes boost/thread/xtime.hpp

Updating the conditional check to apply the Boost TIME_UTC patch resolves this problem and I will be making a pull request shortly with the change.

[easybuild-Boost-1.49.0-20170324.132519.RkuGe.txt](https://github.com/hpcugent/easybuild-easyblocks/files/868772/easybuild-Boost-1.49.0-20170324.132519.RkuGe.txt)

**Comment by boegel** [comment]
Thanks for the report and proposed fix, let's follow-up in #1152
