### ISSUE TITLE
The generic/cmakemake.py use of CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH doesn't work

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-easyblocks#1164]
There is a problems with the current use of CMAKE_INCLUDE_PATH/CMAKE_LIBRARY_PATH.

It is setting CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH based only on the toolchains opinion of LDFLAGS/CPPFLAGS.
I think it would make much more sense to set it to what CPATH and LD_LIBRARY_PATH is instead.

After all, the modules that are (build)dependencies for a piece of code should be picked up by cmake when doing find_path/find_library.

**Comment by wpoely86** [comment]
I can be wrong but aren't both build on the same info? LDFLAGS and CFLAGS use CPATH and LD_LIBRARY_PATH?

**Comment by akesandgren** [comment]
No, self.toolchain.get_variable("CPPFLAGS", list) only contains the paths from the toolchain in use, not any CPATHs added by extra modules, like hwloc which is part of the module chain for foss, but not the actual toolchain.

The problem showed up when building gromacs using foss and actually looking at the build log. It was failing to find the hwloc that is part of the foss/2017a module chain.

**Comment by boegel** [comment]
Let's follow up on this in #1165
