### ISSUE TITLE
when INTEL_LICENSE_FILE env var points to a dir, append every license in dir

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-easyblocks#555]
now if INTEL_LICENSE_FILE is pointing to a directory, just the first license in the directory is used.

EB should do something like INTEL_LICENSE_FILE="LIC1:LIC2:LIC3"

See https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/generic/intelbase.py#L236

**Comment by boegel** [comment]
this is fixed with #839 (which is going to be merged very soon, and will be included in EB v2.7.0)
