### ISSUE TITLE
Improving OpenIFS easyblock

### ISSUE THREAD

**Issue by omula** [hpcugent/easybuild-easyblocks#556]
Hi,

I am trying to make openifs easyblock working with newer version and I've realised that FCM is like EasyBuild and that they provide several configurations for the model.
omula@login:/tmp/oifs38r1v04/make/cfg$ ls -1
cce-nansC.cfg
cce-noopt.cfg
cce-opt.cfg
gnu-nansC.cfg
gnu-noopt.cfg
gnu-opt.cfg
ibm-nansC.cfg
ibm-noopt.cfg
ibm-opt.cfg
intel_mkl-nansC.cfg
intel_mkl-noopt.cfg
intel_mkl-opt.cfg
intel-nansC.cfg
intel-noopt.cfg
intel-opt.cfg
lapack.cfg
oifs-depend.cfg
oifs_xlf_wrapper
pgi-nansC.cfg
pgi-noopt.cfg
pgi-opt.cfg

diff -rupN intel_mkl-opt.cfg intel_mkl-noopt.cfg
--- intel_mkl-opt.cfg	2014-10-13 16:25:37.000000000 +0200
+++ intel_mkl-noopt.cfg	2014-10-13 16:25:37.000000000 +0200
@@ -1,5 +1,5 @@
 #  FCM compiler & build specific configuration file for OpenIFS
-#  intel_mkl compiler, opt build
+#  intel_mkl compiler, noopt build
 
 #          Glenn Carver         ECMWF 2012-2014
 
@@ -30,15 +30,15 @@ $OIFS_SRC_EXCL{?} =
 #  Fortran
 
 $OIFS_FC{?}     = mpiifort
-$OIFS_FFLAGS{?} = -g -m64 -openmp -O1 -xHost -fp-model precise -convert big_endian -traceback
+$OIFS_FFLAGS{?} = -g -m64 -O0 -fp-model precise -convert big_endian -traceback
 $OIFS_FFIXED{?} = -r8
 $OIFS_FCDEFS{?} = BLAS LITTLE LINUX INTEGER_IS_INT
-$OIFS_LFLAGS{?} = -openmp
+$OIFS_LFLAGS{?} = 
 
 # C compiler
 
 $OIFS_CC{?}     = mpiicc
-$OIFS_CFLAGS{?} = -g -O
+$OIFS_CFLAGS{?} = -g -O0
 $OIFS_CCDEFS{?} = BLAS LITTLE LINUX INTEGER_IS_INT _ABI64
 
 # Architecture/compiler specific FCM (if any)

Further information on compiling OpenIFS can be found in https://software.ecmwf.int/wiki/display/OIFS/How+to+customize+compiling+OpenIFS

Which would be the best way to improve the easyblock? You can have a look to my current attempt now in https://github.com/omula/easybuild-easyblocks/tree/develop-openifs

I had to add the -convert big_endian but I don't know if that would be the best solution.

Cheers,
Oriol

**Comment by wpoely86** [comment]
Hi Oriol,

I'm not quite sure what exactly you want to do? What should be added to the current easyblock? In what way doesn't it work?

You want to be able to switch between the `opt` and `noopt` build?

**Comment by boegel** [comment]
Let's get a PR open for https://github.com/omula/easybuild-easyblocks/compare/hpcugent:develop...develop-openifs, and discuss it there. :)

**Comment by boegel** [comment]
@omula: please close this issue if you have an open PR for this

**Comment by boegel** [comment]
see #561
