### ISSUE TITLE
INTEL_LICENSE_FILE gets incorrectly set in created module file for the intel tools when it's defined in the environment as port@host

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-easyblocks#608]
When building an intel tool (icc, ifort etc) the INTEL_LICENSE_FILE setting in the generated module file is messed up if INTEL_LICENSE_FILE is set in the environment at build time to port@host. The result in the module file looks like:
prepend_path("INTEL_LICENSE_FILE", pathJoin(root, "28518@license.hpc2n.umu.se"))

The icc/ifort etc easyblock does:
txt += self.module_generator.prepend_paths(self.license_env_var, [self.license_file], allow_abs=True)
without checing if license_file is really a file or not.

Even if intelbase.py does figure this out, the information (file or port@server) does not seem to get propagated back to icc.py (or i might just be reading it wrong)

**Comment by boegel** [comment]
So, the main issue here is the `pathJoin` bit, right?

It's OK if `port@server` is included in `$INTEL_LICENSE_FILE` in between other values, separated by `:`?

**Comment by akesandgren** [comment]
On 07/01/2015 06:25 PM, Kenneth Hoste wrote:
> So, the main issue here is the `pathJoin` bit, right?
>
> It's OK if `port@server` is included in `$INTEL_LICENSE_FILE` in between other values, separated by `:`?

Yes, port@server separated by : is ok.

-- 
Ake Sandgren, HPC2N, Umea University, S-90187 Umea, Sweden
Internet: ake@hpc2n.umu.se   Phone: +46 90 7866134 Fax: +46 90-580 14
Mobile: +46 70 7716134 WWW: http://www.hpc2n.umu.se

**Comment by boegel** [comment]
fix is available in #635

**Comment by boegel** [comment]
fixed by #635
