### ISSUE TITLE
Cannot build CUDA > 6 with the current easyblocks

### ISSUE THREAD

**Issue by Trefex** [hpcugent/easybuild-easyblocks#634]
With the current easyblock cuda.py, CUDA 6 and 7 fail at the sanity checks as the files it tries to check do not exist in the sources.

Best,

**Comment by fgeorgatos** [comment]
IMHO, this is resolved by now? if agreed, close

**Comment by boegel** [comment]
Confirmed: see https://github.com/hpcugent/easybuild-easyblocks/pull/476 (CUDA 6.x) https://github.com/hpcugent/easybuild-easyblocks/pull/708 (CUDA 7.x).
