### ISSUE TITLE
Ruby gems are not being installed in their own prefix

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-easyblocks#646]
for example:

```
$ module load FPM/1.3.3-Ruby-2.1.6
$ which fpm
/Users/kehoste/.local/easybuild/software/Ruby/2.1.6/bin/fpm
```

cc @rjeschmi

**Comment by rjeschmi** [comment]
I can confirm it is also a problem elsewhere :)

**Comment by boegel** [comment]
`RubyGem` should be specifying `--install-dir`? http://guides.rubygems.org/command-reference/#gem-install

and the FPM easyconfig should include a custom `sanity_check_paths`...

**Comment by boegel** [comment]
Installing FPM will be broken with EasyBuild 2.2.1 unless we fix this, thanks to https://github.com/hpcugent/easybuild-framework/pull/1366

See also https://github.com/hpcugent/easybuild-easyconfigs/pull/1888

**Comment by boegel** [comment]
see #667

**Comment by boegel** [comment]
Let's follow this up in #667 and https://github.com/hpcugent/easybuild-easyconfigs/issues/1889
