### ISSUE TITLE
Python UNICODE size default incompatible with CentOS 7.1

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-easyblocks#651]
Centos 7 is using UCS-4 but the default config option for Python 2.7 (and others?) use Unicode version 2 (UCS-2). We should try to ensure compatibility with the underlying system python modules.

**Comment by boegel** [comment]
Hmm, I'd like to get more info on this...

I may have been bitten by this without realising; I usually have this in my `.bashrc`, which probably is a workaround for this problem:

```
export LANG=en_US.utf8
export LC_ALL=en_US.utf8
```

**Comment by ocaisa** [comment]
The issue only arises when you try to use a system  provided python module with the EB python, in our case the user wanted to use the slurm python module. The fix is trivial in an easyconfig:
```configopts = '--enable-unicode=ucs4 '```
but it would be smarter to figure out whether this is needed or not in the python easyblock (like [this method](http://stackoverflow.com/questions/1446347/how-to-find-out-if-python-is-compiled-with-ucs-2-or-ucs-4))

**Comment by boegel** [comment]
@ocaisa: doing it in the Python easyblock as shown on the SO link makes sense to m

**Comment by ocaisa** [comment]
This is resolved in #817

**Comment by boegel** [comment]
@ocaisa: let's close this and follow-up in #817?
