### ISSUE TITLE
python-meep pylibdir handling problem

### ISSUE THREAD

**Issue by jas02** [hpcugent/easybuild-easyblocks#695]
python-meep package easyblock is broken. Currently, there is inherited method configure_step() that don't handle self.pylibdir variable. So during installation we have self.pylibdir 'UNKNOWN'.

Patch for this is in PR #694 .

**Comment by boegel** [comment]
jas02: no need to open an issue for it if you already have a PR in place, the PR is sufficient, since every PR is an issue too (it's not a coincidence your PR id is one less than this issue) :-)

follow-up via #694, thanks for looking into the fix!
