### ISSUE TITLE
Intel easyblock not setting GXX_ROOT

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-easyblocks#739]
With ifort, if someone is using non-default locales/languages you can run into problems [like this one](https://software.intel.com/en-us/articles/intel-fortran-compiler-for-linux-ifort-error-could-not-find-directory-in-which-g-resides). A hacky solution is to pick up where the installation is and set the corresponding environment variable that intel uses:
```
export GXX_ROOT=`g++ --print-search-dirs | head -n1 | awk '{print $2}'`
```
though it could definitely be solved more elegantly in the easyblock.

**Comment by boegel** [comment]
@ocaisa: why not use `$EBROOTIFORT`?

**Comment by ocaisa** [comment]
I don't understand, the value for `GXX_ROOT` comes from the `GCC` installation and has nothing to do with where `ifort` is actually installed.

**Comment by ocaisa** [comment]
To have icc/ifort set that variable I need to parse a small piece of `g++ --print-search-dirs`, which is something that would work best in the easyblock.

**Comment by boegel** [comment]
Ah, ok, I missed that, sorry...

Well, for ifort installations on top of a EB-provided GCC, that's trivial I guess.

But using the output obtained from `g++ --print-search-dirs` should be fairly easy to do programatically. I guess this should be done in the `IntelBase` easyblock?

**Comment by ocaisa** [comment]
See #747

**Comment by boegel** [comment]
follow-up in #747
