### ISSUE TITLE
support for 2016.* versions of Intel tools

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-easyblocks#751]
Overview of issues related to supporting the installation of the 2016.* versions of the Intel tools.

relevant pull requests:

* patched `EB_icc` easyblock: ~~https://github.com/hpcugent/easybuild-easyblocks/pull/691~~, https://github.com/hpcugent/easybuild-easyblocks/pull/756
* 2016.0.109: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/1973~~
* 2016.1.150: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2148~~
* compatibility with GCC 5.x: https://github.com/hpcugent/easybuild-easyconfigs/issues/2100

**Comment by wpoely86** [comment]
#756 has the latest intel easyblocks.

**Comment by boegel** [comment]
all PRs merged
