### ISSUE TITLE
Problem with logic for use of SCOTCH_PTHREAD

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-easyblocks#795]
Currenty in [this line](https://github.com/hpcugent/easybuild-easyblocks/blob/develop/easybuild/easyblocks/s/scotch.py#L111) we switch off the use of `SCOTCH_PTHREAD` for some MPI implementattions. ParaStation MPI has both threadsafe and non-threadsafe versions so we need the ability to turn this feature on or off from the easyconfig file too.

**Comment by boegel** [comment]
up for tackling this yourself @ocaisa? or @damianam?

**Comment by ocaisa** [comment]
We've done a modified EasyBlock that accepts `threadedmpi = True` in the easyconfig. Will contribute back when we get a chance to take a breath

**Comment by boegel** [comment]
@ocaisa great!

**Comment by fgeorgatos** [comment]
@ocaisa, @boegel: thanks, this ringed a bell! #166 could have been helped by it.
When I have a crumb of time, I'd give it another spin just out of curiosity.

**Comment by boegel** [comment]
@ocaisa breathing yet? ;)

**Comment by boegel** [comment]
follow-up in PR #914 that tackles this, thanks @ocaisa
