### ISSUE TITLE
Misbehaving PGI compiler when installed with EB

### ISSUE THREAD

**Issue by damianam** [hpcugent/easybuild-easyblocks#830]
@bartoldeman and @ocaisa are probably interested in this.

The PGI compiler misbehaves when using certain C++ features, but just when installed with EB. The reason is that `$CPATH` gets defined to include `linux86-64/15.10/include`. In the modules shipped with PGI `$CPATH` is not defined anywhere.

This file:

```c++
#include <iostream>

int main(){
    std::cout << __INTMAX_MAX__ << '\n';
    return 0;
}
```

Compiles with this command (when loading the PGI module shipped with PGI itself):

`pgc++ example.cpp `

When loading the EB-created module the same command spits this error:

```
"example.cpp", line 4: error: identifier "__INTMAX_MAX__" is undefined
      std::cout << __INTMAX_MAX__ << '\n';
                   ^

1 error detected in the compilation of "example.cpp".
```

PGI also provides different sets of includes in `linux86-64/15.10/include-gccXX`. Under some circumstances, prepending that path to `$CPATH` works. In this specific example it doesn't, and fails with this error:

```
"/usr/include/pthread.h", line 397: error: identifier "cpu_set_t" is undefined
                                        const cpu_set_t *__cpuset)
                                              ^

"/usr/include/pthread.h", line 404: error: identifier "cpu_set_t" is undefined
                                        cpu_set_t *__cpuset)
                                        ^

"/usr/include/pthread.h", line 466: error: identifier "cpu_set_t" is undefined
                                   const cpu_set_t *__cpuset)
                                         ^

"/usr/include/pthread.h", line 471: error: identifier "cpu_set_t" is undefined
                                   cpu_set_t *__cpuset)
                                   ^

"/usr/local/software/jureca/Stage1/software/Core/GCC-bare/4.9.3/include/c++/4.9.3/x86_64-unknown-linux-gnu/bits/gthr-default.h", line 692: error: 
          identifier "sched_yield" is undefined
    return __gthrw_(sched_yield) ();
           ^

5 errors detected in the compilation of "example.cpp".
```

I propose to avoid defining `$CPATH` in the PGI easyblock, mimicking the behaviour of the modules shipped with PGI. I can prepare a PR if everyone agrees.

**Comment by boegel** [comment]
Is it worth asking PGI support wth is going on, i.e. why 'broken' header files are shipped with PGI, and why it's wrong to add the path to those header files to `$CPATH`?

I'm all for not defining `$CPATH` btw, should be fairly trivial to make that change (or should I say 'easy', since this is *Easy*Build? ;-))

**Comment by damianam** [comment]
@boegel I guess it is just how PGI works. I mean, in their modules `$CPATH` is not set, from my perspective our modules should try to mimic existing ones, unless for whatever reason we have to add something to improve it. But it doesn't seem to be the case.

@bartoldeman do you have any feedback? I have an easyblock ready for a PR, but I'd like to count with the opinion of the original author.

**Comment by boegel** [comment]
@damianam: just open the PR, it's easier to discuss it there through inline comments? feedback from @bartoldeman would be nice indeed :)

**Comment by damianam** [comment]
Done (https://github.com/hpcugent/easybuild-easyblocks/pull/837)

**Comment by boegel** [comment]
Let's follow this up in #837, where this problem is being fixed
