### ISSUE TITLE
Totalview fails when license server is used instead of license file

### ISSUE THREAD

**Issue by surak** [hpcugent/easybuild-easyblocks#851]
Totalview's easyblock ( https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/t/totalview.py ) checks for a license FILE. This will fail when the license is actually in a server. 

Totalview will check for the license in one of these two ways:
    - Inside the file
    - Point to a license server with the environment variable LM_LICENSE_FILE

The license "file" can't point to the license server, it only accepts a license itself. So, Easybuild must

1) Accept to install totalview without a license file
2) Be able to receive a parameter (or on the EasyConfig) that creates the LM_LICENSE_FILE properly pointing to multiple servers, without needing the file.

**Comment by boegel** [comment]
Sounds like the TotalView easyblock could make good use of the `find_flexlm_license ` function that was fleshed out from the `IntelBase` easyblock: https://github.com/hpcugent/easybuild-framework/pull/1633...

**Comment by damianam** [comment]
There you go: https://github.com/hpcugent/easybuild-easyblocks/pull/857

@surak once this gets merged you can clean up your ebs a bit (`modextrapaths` and `modextravars` are no longer necessary, and in our environment the license is picked up automatically, so `license_file` can go as well)

**Comment by surak** [comment]
Damian, the license is only picked when some module is loaded, am I right? That's why I kept it at the .EB file, so it generates the same env var at the Totalview module.

**Comment by damianam** [comment]
That environment variable is handled (and added to the module file) now by the easyblock, so you don't have to have it anywhere in the .eb. Unless there is no `LM_LICENSE_FILE` defined in the environment. Which in our environment shouldn't happen, since it defined when loading the modules necessary to install software.

**Comment by surak** [comment]
Totalview needs the LM_LICENSE_FILE to run, and it checks it every time you tell it to run a code, so it is pointless to have it while installing (it doesn't check for a license when it is installed at all).

**Comment by damianam** [comment]
It is not about using the license during installation, it is about knowing which license to use, so easybuild can set up the modules correctly and set the proper environment variable in the module.

**Comment by boegel** [comment]
fixed with #857, so can we close this?

**Comment by surak** [comment]
Yeap :-)
