### ISSUE TITLE
allow setting components for imkl easyblock

### ISSUE THREAD

**Issue by andreas-h** [hpcugent/easybuild-easyblocks#899]
The imkl easyblock contains the following lines in `install_step()`:

    if LooseVersion(self.version) >= LooseVersion('11.1'):
        silent_cfg_extras = {
            'COMPONENTS': 'ALL',
        }

On Intel MKL 11.3, this effectively prevents setting a `components` list in the easyconfig, which means that when installing from the full Intel tarball (e.g., `parallel_studio_xe_2016_update2.tgz`), the `imkl/VERSION` directory in `software/` becomes many Gb large.

When I remove the above mentioned lines from the easyblock and insert 

    components = ['intel-mkl']

in the easyconfig, the software directory becomes a (still large, but more reasonable) 2.7Gb.

Is there any specific reason why the `COMPONENTS` are being set to `ALL`? Or would it make more sense to check in the easyblock if a `components` config value has been set in the easyconfig, and only set `COMONENTS` to `ALL` if there are no components explicitly specified?

**Comment by andreas-h** [comment]
@wpoely86 since the component setting comes from her/him.

**Comment by wpoely86** [comment]
@andreas-h Yes, we should bring the mkl and impi block to the same level as icc and icpc. It's been on my todo list for quite some time. I will try to get it done.

**Comment by boegel** [comment]
+1, makes sense

@andreas-h up for tackling this yourself? You seem to be able to find your way around quite well. :)

**Comment by andreas-h** [comment]
> @andreas-h up for tackling this yourself? You seem to be able to find your way around quite well. :)

I can sure do so, but my 'fix' is to simply remove those lines i quoted.
However, I'm sure they've been introduced for a reason, which is why I'm
hesitating, as I don't have a feeling for the implications of the change.

**Comment by boegel** [comment]
@andreas-h I think it's because the `COMPONENTS` key *has* to be defined for imkl 11.1 and more recent; see also https://software.intel.com/en-us/articles/intel-mkl-111-install-guide (look for `silent.cfg`).

Your idea of checking whether `components` is specified and falling back to setting `ALL` if not seems like the right approach to me?

**Comment by wpoely86** [comment]
I've looked at it. I think we need to change a single line. Will test if it works

**Comment by boegel** [comment]
fixed in #943
