### ISSUE TITLE
impi MIC_LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by stachon** [hpcugent/easybuild-easyblocks#917]
I think impi should set MIC_LD_LIBRARY_PATH (in the same way as imkl already does) to mic/lib/

**Comment by boegel** [comment]
@stachon makes sense... up for looking into a PR for that?

**Comment by stachon** [comment]
ok I will prepare a PR

**Comment by boegel** [comment]
@stachon fixed in #925, so can be closed?

**Comment by stachon** [comment]
yes, thanks!
