### ISSUE TITLE
Investigate creation of a `siterc` file for PGI to support `$LIBRARY_PATH`

### ISSUE THREAD

**Issue by geimer** [hpcugent/easybuild-easyblocks#918]
Quoting from https://github.com/hpcugent/easybuild/issues/217:

Apparently `$LIBRARY_PATH` is ignored by the PGI compilers. However, the GCCcore stuff is correctly picked up via the `localrc` file generated by the `makelocalrc` script run during installation. To make `$LIBRARY_PATH` work, PGI proposes a workaround on their web pages, see https://www.pgroup.com/support/link.htm#lib_path_ldflags.

Note that there is a typo in the code snippet. The second line should read `$LIBRARY_PATH` from the environment, not `$LD_LIBRARY_PATH`.

It should also be straightforward to add `/usr/lib/x86_64-linux-gnu` to `$LIBRARY_PATH` in the module file directly from the PGI easyblock when on a Debian/Ubuntu system, to work around the issue linked above.

**Comment by boegel** [comment]
@damianam, @bartoldeman thoughts on this?

PGI not picking up `$LIBRARY_PATH` is going to bite us in the ass sooner or later, we're bound to rely on it in several places since `$LIBRARY_PATH` is defined by the modules generated by EB...

**Comment by damianam** [comment]
That's a PITA. I see 2 approaches:

* We patch the installation as suggested in Marku's link. The change is permanent for everyone.
* We redefine `LIBRARY_PATHS` to `LDLIBARGS` in EB (I am not sure where though).

The first approach changes the default behaviour, but will make things easier for new PGI users. The second approach respect the default behaviour, but it will be more work to implement and will left new users exposed to this annoyance. I'd suggest to go for the first one.

**Comment by boegel** [comment]
Since installing a custom `siterc` file is an official recommendation by PGI, I'd definitely go with that...

**Comment by damianam** [comment]
Seems more like a workaround than a recommendation, but yes, I agree, it looks like the best option.

**Comment by bartoldeman** [comment]
Agreed, siterc is the way to go

**Comment by boegel** [comment]
fixed in #919, please review?

**Comment by boegel** [comment]
let's follow up in #919, there's no use in tracking this in two issues
