### ISSUE TITLE
ACTIVATION_LICENSE_FILE not defined in silent.cfg when installing impi (regression in EasyBuild v2.7.0)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-easyblocks#933]
Problem reported by @MalkinE via the EasyBuild mailing list, cfr. https://lists.ugent.be/wws/arc/easybuild/2016-05/msg00035.html

**Comment by boegel** [comment]
According to the info provided and the implementation in `IntelBase`, it seems like this was the behaviour with EasyBuild v2.6.0 (I had to do a little bit of guessing because no full debug log was provided):

* no valid license specs found via either `$INTEL_LICENSE_FILE` or `$LM_LICENSE_FILE`
* fall back to using specified path via `license_file` easyconfig parameter (`$HOME/licenses/intel/license.lic`)
* use `license_server` as value for `ACTIVATION_TYPE` (default)
* specify `license_file` value for `ACTIVATION_LICENSE_FILE`

While with EasyBuild v2.7.0, it seems like the following occurs:

* *multiple* 'valid' license specs found via either `$INTEL_LICENSE_FILE` or `$LM_LICENSE_FILE`
* disregard value for `license_file` parameter (no fallback needed)
* use `exist_lic` as value for `ACTIVATION_TYPE` since *multiple* valid license specs were found
* don't specify any value for `ACTIVATION_LICENSE_FILE`, since activation type is `exist_lic`
* valid license is expected to be specified via either `$INTEL_LICENSE_FILE` or `$LM_LICENSE_FILE`

The `find_flexlm_license` function that was introduced in https://github.com/hpcugent/easybuild-framework/pull/1633 and using by `IntelBase` since then does try a bit harder to find valid license specifications via `$INTEL_LICENSE_FILE` or `$LM_LICENSE_FILE`.

This seems to be mostly this: if a directory is specified, *all* `*.lic` and `*.dat` files are considered valid license files; before, only the first `.*lic` file was retained.

@MalkinE: does this match with your setup?

If so, then I'm not sure whether this is actually a regression...
The end result is different, but only because EasyBuild does a better job at trying to find license files.

**Comment by boegel** [comment]
Thanks to debug logs provided by @MalkinE, I was able to pinpoint the regression to the function `find_flexlm_license` returning a list with duplicate entries, cfr. https://github.com/hpcugent/easybuild-framework/pull/1779 .

That explain why `IntelBase` was finding 'multiple' valid license; in fact, there was only one, but it got a list with the same license file listed multiple times.

What's still unclear is why the fallback to using `exist_lic` and defining `$INTEL_LICENSE_FILE` (with multiple entries) didn't work. I tried to reproduce this, and it worked fine for me (and @pescobar also confirmed that he uses a setup where `$INTEL_LICENSE_FILE` points to multiple (different) license files, which works fine).

So, as far as I can tell, there is no issue in `IntelBase` at all. It seems like the Intel installer has trouble with `exist_lic` on @MalkinE's system, possibly due to problem with the FlexLM license server being used (but this is just a guess)...

**Comment by boegel** [comment]
https://github.com/hpcugent/easybuild-framework/pull/1779 is merged, and I added some more debug info to `IntelBase`  (cfr. #936).

There's little more we can do on the EasyBuild side of things though, since my tests and the observations by @pescobar confirm that there's no bug in `IntelBase` itself.

@MalkinE: do you agree, and can we close this issue?

**Comment by MalkinE** [comment]
I agree. From the manual installation that I tried it seems that this is an issue with Intel (or the FlexLM as @boegel mentioned), not EasyBuild. After implementing the bug fix I was able to install impi and imkl with EB 2.7, so it at least solves the problem at hand, even if we don't fully understand the reason for the crash. We can close the issue.

**Comment by boegel** [comment]
Thanks for the confirmation @MalkinE!
