### ISSUE TITLE
MRtrix 0.3.14 Build fails.

### ISSUE THREAD

**Issue by lekshmideepu** [hpcugent/easybuild-easyblocks#948]
I came across the following error message when I try to install MRtrix 0.3.14. On the other hand, manual installation in the same environment is successful.

build failed (first 300 chars): cmd "python configure -verbose" exited with exitcode 1 and output:
MRtrix build type requested: release
Detecting OS: linux
Machine architecture set by ARCH environment variable to: x86-64
Checking for C++11 compliant compiler [g++]: EXEC <<
CMD: g++ -dumpversion
EXIT: 0
STDOUT:
4.9.3
>>
4.9.3
CO

Any help will be appreciated!

**Comment by boegel** [comment]
@lekshmideepu it seems like this output is incomplete, this doens't seem to explain the actual problem...

Can you make the full log file (preferably a debug log, collected using `eb --debug`) available somewhere (e.g. via https://gist.github.com/)?

**Comment by boegel** [comment]
@lekshmideepu Also, which EasyBuild version are you using?

There are some critical updates to the MRtrix easyblock included in EasyBuild v2.8.1, cfr. #932?

**Comment by lekshmideepu** [comment]
Easybuilz version 2.8.0. I am using the latest fix patch too.

**Comment by lekshmideepu** [comment]
https://gist.github.com/lekshmideepu/1fbc63cf077d45e1eee444c543b052bf

**Comment by boegel** [comment]
@lekshmideepu please try again with EasyBuild v2.8.1 which was released earlier this week (see http://easybuild.readthedocs.io/en/latest/Release_notes.html#release-notes).

The gist shows that you're still using the MRtrix easyblock that's not aware of v0.3.14 yet; in particular, it is still setting `$LD` and `$LDLIB` (incorrectly, for v0.3.14), cfr. https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/m/mrtrix.py#L58

**Comment by lekshmideepu** [comment]
It is working now! Thanks for the help.

**Comment by boegel** [comment]
:+1:
