### ISSUE TITLE
cp2k easyblock ignores --optarch=GENERIC

### ISSUE THREAD

**Issue by simo-tuomisto** [hpcugent/easybuild-easyblocks#975]
In cp2k.py:438:
optarch = ''
if self.toolchain.options['optarch']:
   optarch = '-xHOST'

and cp2k.py:484:
optarch = ''
if self.toolchain.options['optarch']:
   optarch = '-march=native'

Is this behaviour intended?

**Comment by boegel** [comment]
@simo-tuomisto I just noticed this was left unanswered...

This is indeed a bug in the CP2K easyblock that we should fix.

The `-xHOST` and `-march=native` should indeed not be hardcoded in the CP2K easyblock, they should come from the toolchain mechanism. In that case, CP2K would also be built as intended under `--optarch=GENERIC` or `--optarch=<custom flags>`.

**Comment by boegel** [comment]
@damianam while you're at it... ;)

**Comment by boegel** [comment]
Or maybe I'll tackle this myself in the CP2K easyblock update at https://github.com/hpcugent/easybuild-easyblocks/pull/1084, and ask @damianam to review it, since he's familiar both with the CP2K easyblock and the `optarch` use in there.

**Comment by boegel** [comment]
fixedin #1084
